### ISSUE TITLE
I just recently got into CODEQL and don't know what's going on below

### ISSUE THREAD

**Issue by LVLlvs** [github/vscode-codeql-starter#112]
Content-Length: 190

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-cpp/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-cpp, with library path [] and dbscheme Optional.empty
Content-Length: 346

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/misc/legacy-support/csharp/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql/csharp-all"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\misc\legacy-support\csharp, with library path [] and dbscheme Optional.empty
Content-Length: 191

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-java/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-java, with library path [] and dbscheme Optional.empty
Content-Length: 189

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-go/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-go, with library path [] and dbscheme Optional.empty
Content-Length: 197

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-javascript, with library path [] and dbscheme Optional.empty
Content-Length: 346

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/misc/legacy-support/python/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql/python-all"}]}}Content-Length: 193

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-python/qlpack.yml","diagnostics":[]}}Content-Length: 350

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/misc/legacy-support/javascript/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql-javascript"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\misc\legacy-support\python, with library path [] and dbscheme Optional.empty
[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-python, with library path [] and dbscheme Optional.empty
[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\misc\legacy-support\javascript, with library path [] and dbscheme Optional.empty
Content-Length: 181

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/swift/ql/test/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\swift\ql\test, with library path [] and dbscheme Optional.empty
Content-Length: 342

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/misc/legacy-support/java/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql/java-all"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\misc\legacy-support\java, with library path [] and dbscheme Optional.empty
Content-Length: 193

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-custom-queries-csharp/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-custom-queries-csharp, with library path [] and dbscheme Optional.empty
Content-Length: 340

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/misc/legacy-support/cpp/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql/cpp-all"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\misc\legacy-support\cpp, with library path [] and dbscheme Optional.empty
Content-Length: 343

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/codeql-go/ql/config/legacy-support/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Dependency not found: codeql-go"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\codeql-go\ql\config\legacy-support, with library path [] and dbscheme Optional.empty
Content-Length: 180

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/swift/ql/lib/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\swift\ql\lib, with library path [] and dbscheme Optional[D:\Private\security\codeQL\vscode-codeql-starter\ql\swift\ql\lib\swift.dbscheme]
Content-Length: 184

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/swift/ql/lib/swift.dbscheme","diagnostics":[]}}Content-Length: 165

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/codeql/legacy-upgrades/qlpack.yml","diagnostics":[]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\codeql\legacy-upgrades, with library path [] and dbscheme Optional.empty
Content-Length: 843

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/java/ql/lib/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Error reading D:\\Private\\security\\codeQL\\vscode-codeql-starter\\ql\\java\\ql\\lib\\qlpack.yml: Unrecognized field \"groups\" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (14 known properties: \"license\", \"dbscheme\", \"extractor\", \"libraryPathDependencies\", \"repository\", \"name\", \"upgrades\", \"version\", \"library\", \"description\", \"downgrades\", \"tests\", \"dependencies\", \"suites\"])\n at [Source: (StringReader); line: 3, column: 13] (through reference chain: com.semmle.frontend.packs.QlPack[\"groups\"])"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\java\ql\lib, with library path [] and dbscheme Optional.empty
Content-Length: 890

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/csharp/ql/campaigns/Solorigate/lib/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Error reading D:\\Private\\security\\codeQL\\vscode-codeql-starter\\ql\\csharp\\ql\\campaigns\\Solorigate\\lib\\qlpack.yml: Unrecognized field \"groups\" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (14 known properties: \"license\", \"dbscheme\", \"extractor\", \"libraryPathDependencies\", \"repository\", \"name\", \"upgrades\", \"version\", \"library\", \"description\", \"downgrades\", \"tests\", \"dependencies\", \"suites\"])\n at [Source: (StringReader); line: 4, column: 5] (through reference chain: com.semmle.frontend.packs.QlPack[\"groups\"])"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\csharp\ql\campaigns\Solorigate\lib, with library path [] and dbscheme Optional.empty
Content-Length: 842

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/Private/security/codeQL/vscode-codeql-starter/ql/ruby/ql/src/qlpack.yml","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"Error reading D:\\Private\\security\\codeQL\\vscode-codeql-starter\\ql\\ruby\\ql\\src\\qlpack.yml: Unrecognized field \"groups\" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (14 known properties: \"license\", \"dbscheme\", \"extractor\", \"libraryPathDependencies\", \"repository\", \"name\", \"upgrades\", \"version\", \"library\", \"description\", \"downgrades\", \"tests\", \"dependencies\", \"suites\"])\n at [Source: (StringReader); line: 4, column: 3] (through reference chain: com.semmle.frontend.packs.QlPack[\"groups\"])"}]}}[2022-05-04 16:08:44] Creating pack project at D:\Private\security\codeQL\vscode-codeql-starter\ql\ruby\ql\src, with library path [] and dbscheme Optional.empty
May 04, 2022 4:08:44 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at com.semmle.queryserver.client.JsonRpcLauncher.lambda$startListening$0(JsonRpcLauncher.java:50)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: Error processing queries.xml file for query directory D:\Private\security\codeQL\vscode-codeql-starter\ql\ruby\ql\src: Invalid value 'ruby' for language attribute
	at com.semmle.util.xml.XmlErrorHandler.reportErrorsIfAny(XmlErrorHandler.java:46)
	at com.semmle.api.QueryDirectory$Resolver.fromDir(QueryDirectory.java:320)
	at com.semmle.api.QueryDirectory$Resolver.forFile(QueryDirectory.java:332)
	at com.semmle.api.QueryDirectory.forPath(QueryDirectory.java:112)
	at com.semmle.frontend.imports.QueryImportResolver.getImportablePaths(QueryImportResolver.java:183)
	at com.semmle.frontend.QueryLocationGuesser.<init>(QueryLocationGuesser.java:47)
	at com.semmle.frontend.project.QLProject.<init>(QLProject.java:179)
	at com.semmle.frontend.project.QLProject.createProject(QLProject.java:153)
	at com.semmle.frontend.project.ProjectsMap.reloadPackProjects(ProjectsMap.java:142)
	at com.semmle.frontend.project.ProjectsMap.setWorkspaceRoots(ProjectsMap.java:157)
	at com.semmle.frontend.server.QLLanguageServer.initialize(QLLanguageServer.java:219)
	... 16 more

Content-Length: 2916

{"jsonrpc":"2.0","id":0,"error":{"code":-32603,"message":"Internal error.","data":"java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\r\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\r\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\r\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\r\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\r\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\r\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\r\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\r\n\tat com.semmle.queryserver.client.JsonRpcLauncher.lambda$startListening$0(JsonRpcLauncher.java:50)\r\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.base/java.lang.Thread.run(Unknown Source)\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\r\n\t... 11 more\r\nCaused by: Error processing queries.xml file for query directory D:\\Private\\security\\codeQL\\vscode-codeql-starter\\ql\\ruby\\ql\\src: Invalid value \u0027ruby\u0027 for language attribute\r\n\tat com.semmle.util.xml.XmlErrorHandler.reportErrorsIfAny(XmlErrorHandler.java:46)\r\n\tat com.semmle.api.QueryDirectory$Resolver.fromDir(QueryDirectory.java:320)\r\n\tat com.semmle.api.QueryDirectory$Resolver.forFile(QueryDirectory.java:332)\r\n\tat com.semmle.api.QueryDirectory.forPath(QueryDirectory.java:112)\r\n\tat com.semmle.frontend.imports.QueryImportResolver.getImportablePaths(QueryImportResolver.java:183)\r\n\tat com.semmle.frontend.QueryLocationGuesser.\u003cinit\u003e(QueryLocationGuesser.java:47)\r\n\tat com.semmle.frontend.project.QLProject.\u003cinit\u003e(QLProject.java:179)\r\n\tat com.semmle.frontend.project.QLProject.createProject(QLProject.java:153)\r\n\tat com.semmle.frontend.project.ProjectsMap.reloadPackProjects(ProjectsMap.java:142)\r\n\tat com.semmle.frontend.project.ProjectsMap.setWorkspaceRoots(ProjectsMap.java:157)\r\n\tat com.semmle.frontend.server.QLLanguageServer.initialize(QLLanguageServer.java:219)\r\n\t... 16 more\r\n"}}[Error - 16:08:44] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at com.semmle.queryserver.client.JsonRpcLauncher.lambda$startListening$0(JsonRpcLauncher.java:50)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: Error processing queries.xml file for query directory D:\Private\security\codeQL\vscode-codeql-starter\ql\ruby\ql\src: Invalid value 'ruby' for language attribute
	at com.semmle.util.xml.XmlErrorHandler.reportErrorsIfAny(XmlErrorHandler.java:46)
	at com.semmle.api.QueryDirectory$Resolver.fromDir(QueryDirectory.java:320)
	at com.semmle.api.QueryDirectory$Resolver.forFile(QueryDirectory.java:332)
	at com.semmle.api.QueryDirectory.forPath(QueryDirectory.java:112)
	at com.semmle.frontend.imports.QueryImportResolver.getImportablePaths(QueryImportResolver.java:183)
	at com.semmle.frontend.QueryLocationGuesser.<init>(QueryLocationGuesser.java:47)
	at com.semmle.frontend.project.QLProject.<init>(QLProject.java:179)
	at com.semmle.frontend.project.QLProject.createProject(QLProject.java:153)
	at com.semmle.frontend.project.ProjectsMap.reloadPackProjects(ProjectsMap.java:142)
	at com.semmle.frontend.project.ProjectsMap.setWorkspaceRoots(ProjectsMap.java:157)
	at com.semmle.frontend.server.QLLanguageServer.initialize(QLLanguageServer.java:219)
	... 16 more

[Error - 16:08:44] Starting client failed
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at com.semmle.queryserver.client.JsonRpcLauncher.lambda$startListening$0(JsonRpcLauncher.java:50)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: Error processing queries.xml file for query directory D:\Private\security\codeQL\vscode-codeql-starter\ql\ruby\ql\src: Invalid value 'ruby' for language attribute
	at com.semmle.util.xml.XmlErrorHandler.reportErrorsIfAny(XmlErrorHandler.java:46)
	at com.semmle.api.QueryDirectory$Resolver.fromDir(QueryDirectory.java:320)
	at com.semmle.api.QueryDirectory$Resolver.forFile(QueryDirectory.java:332)
	at com.semmle.api.QueryDirectory.forPath(QueryDirectory.java:112)
	at com.semmle.frontend.imports.QueryImportResolver.getImportablePaths(QueryImportResolver.java:183)
	at com.semmle.frontend.QueryLocationGuesser.<init>(QueryLocationGuesser.java:47)
	at com.semmle.frontend.project.QLProject.<init>(QLProject.java:179)
	at com.semmle.frontend.project.QLProject.createProject(QLProject.java:153)
	at com.semmle.frontend.project.ProjectsMap.reloadPackProjects(ProjectsMap.java:142)
	at com.semmle.frontend.project.ProjectsMap.setWorkspaceRoots(ProjectsMap.java:157)
	at com.semmle.frontend.server.QLLanguageServer.initialize(QLLanguageServer.java:219)
	... 16 more

**Comment by adityasharad** [comment]
Thanks for your interest in using CodeQL. I recommend asking future questions in the https://github.com/github/codeql repo since we monitor that more frequently for user questions and suggestions.

For your issue, could you please share which version of the CodeQL extension for VS Code you are using, and which version of the CodeQL CLI? In VS Code you can find this information by clicking the `CodeQL CLI v2.*.*` taskbar icon in the bottom right.

**Comment by jketema** [comment]
Assuming this has been resolved or moved to the CodeQL repo.
