### ISSUE TITLE
Resolving library paths fails

### ISSUE THREAD

**Issue by wulfland** [github/vscode-codeql-starter#92]
I just cloned the starter workspace on my new macbook and it failed with the error below. Also tried it in a new Codespaces image and I get the same error. I made sure to initialise all submodules with `git submodules update --init`. This worked two weeks ago on my windows machine without problems. Do I miss anything or is this somehow broken?

<details>
<summary>Logile</summary>

```
Resolving library paths using CodeQL CLI: resolve library-path -v --log-to-stderr --format json --query /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/example.ql --additional-packs /workspaces/vscode-codeql-starter/codeql-custom-queries-cpp:/workspaces/vscode-codeql-starter/codeql-custom-queries-csharp:/workspaces/vscode-codeql-starter/codeql-custom-queries-go:/workspaces/vscode-codeql-starter/codeql-custom-queries-java:/workspaces/vscode-codeql-starter/codeql-custom-queries-javascript:/workspaces/vscode-codeql-starter/codeql-custom-queries-python:/workspaces/vscode-codeql-starter/codeql-custom-queries-ruby:/workspaces/vscode-codeql-starter/codeql-go:/workspaces/vscode-codeql-starter/ql...
Sending shutdown request
Sent shutdown request
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving query at normalized path /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/example.ql.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Found enclosing pack 'getting-started/codeql-extra-queries-javascript' at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Adding compilation cache at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/.cache.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving library dependencies from /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml.
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Error reading /workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json: Unrecognized field "versionPolicies" (class com.semmle.frontend.packs.QlWorkspace$ManifestFile), not marked as ignorable (3 known properties: "provide", "ignore", "chainToAncestor"])
                               at [Source: (String)"{
                                  "provide": [
                                      "*/ql/src/qlpack.yml",
                                      "*/ql/lib/qlpack.yml",
                                      "*/ql/test/qlpack.yml",
                                      "*/ql/examples/qlpack.yml",
                                      "*/upgrades/qlpack.yml",
                                      "cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml",
                                      "misc/legacy-support/*/qlpack.yml",
                                      "misc/suite-helpers/qlpack.yml","[truncated 296 chars]; line: 16, column: 25] (through reference chain: com.semmle.frontend.packs.QlWorkspace$ManifestFile["versionPolicies"]) (/workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json:1,1-1)
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Referenced pack 'codeql/javascript-all' not found. (/workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml:1,1-1)
[2021-12-08 18:25:50] Exiting with code 1

Resolving library paths failed: [2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving query at normalized path /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/example.ql.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Found enclosing pack 'getting-started/codeql-extra-queries-javascript' at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Adding compilation cache at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/.cache.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving library dependencies from /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml.
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Error reading /workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json: Unrecognized field "versionPolicies" (class com.semmle.frontend.packs.QlWorkspace$ManifestFile), not marked as ignorable (3 known properties: "provide", "ignore", "chainToAncestor"])
                               at [Source: (String)"{
                                  "provide": [
                                      "*/ql/src/qlpack.yml",
                                      "*/ql/lib/qlpack.yml",
                                      "*/ql/test/qlpack.yml",
                                      "*/ql/examples/qlpack.yml",
                                      "*/upgrades/qlpack.yml",
                                      "cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml",
                                      "misc/legacy-support/*/qlpack.yml",
                                      "misc/suite-helpers/qlpack.yml","[truncated 296 chars]; line: 16, column: 25] (through reference chain: com.semmle.frontend.packs.QlWorkspace$ManifestFile["versionPolicies"]) (/workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json:1,1-1)
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Referenced pack 'codeql/javascript-all' not found. (/workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml:1,1-1)
[2021-12-08 18:25:50] Exiting with code 1
 (codeQL.runQuery)
Error: Resolving library paths failed: [2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving query at normalized path /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/example.ql.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Found enclosing pack 'getting-started/codeql-extra-queries-javascript' at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Adding compilation cache at /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/.cache.
[2021-12-08 18:25:50] [DETAILS] resolve library-path> Resolving library dependencies from /workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml.
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Error reading /workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json: Unrecognized field "versionPolicies" (class com.semmle.frontend.packs.QlWorkspace$ManifestFile), not marked as ignorable (3 known properties: "provide", "ignore", "chainToAncestor"])
                               at [Source: (String)"{
                                  "provide": [
                                      "*/ql/src/qlpack.yml",
                                      "*/ql/lib/qlpack.yml",
                                      "*/ql/test/qlpack.yml",
                                      "*/ql/examples/qlpack.yml",
                                      "*/upgrades/qlpack.yml",
                                      "cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml",
                                      "javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml",
                                      "misc/legacy-support/*/qlpack.yml",
                                      "misc/suite-helpers/qlpack.yml","[truncated 296 chars]; line: 16, column: 25] (through reference chain: com.semmle.frontend.packs.QlWorkspace$ManifestFile["versionPolicies"]) (/workspaces/vscode-codeql-starter/ql/.codeqlmanifest.json:1,1-1)
[2021-12-08 18:25:50] [ERROR] resolve library-path> ERROR: Referenced pack 'codeql/javascript-all' not found. (/workspaces/vscode-codeql-starter/codeql-custom-queries-javascript/qlpack.yml:1,1-1)
[2021-12-08 18:25:50] Exiting with code 1

    at CodeQLCliServer.runCodeQlCliInternal (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/cli.js:203:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CodeQLCliServer.runJsonCodeQlCliCommand (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/cli.js:366:24)
    at CodeQLCliServer.resolveLibraryPath (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/cli.js:385:16)
    at Object.compileAndRunQueryAgainstDatabase (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/run-queries.js:449:24)
    at compileAndRunQuery (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/extension.js:321:26)
    at ctx.subscriptions.push.commandRunner_1.commandRunnerWithProgress.title (/home/codespace/.vscode-remote/extensions/github.vscode-codeql-1.5.8/out/extension.js:390:121)
```

<details>

**Comment by aeisenberg** [comment]
You have caught us partway through releasing new features. We have changed the way codeql workspaces are specified and changed the submodules in the starter workspace before releasing the version of the CLI that can read those changes. The simplest fix for you is to check out an older version of the submodule.

Go into the `ql` directory and run:

```
git checkout codeql-cli/v2.7.2
```

and run the same command in codeql-go.

**Comment by wulfland** [comment]
That worked. Thanks for the help. That's why I keep telling people not to use submodules for managing dependencies 🤣

**Comment by Aaron911** [comment]
> You have caught us partway through releasing new features. We have changed the way codeql workspaces are specified and changed the submodules in the starter workspace before releasing the version of the CLI that can read those changes. The simplest fix for you is to check out an older version of the submodule.
> 
> Go into the `ql` directory and run:
> 
> ```
> git checkout codeql-cli/v2.7.2
> ```
> 
> and run the same command in codeql-go.

Hello, I encountered the similar problems. Here is the log. 
`[2021-12-14 20:30:36] [ERROR] resolve library-path> ERROR: Error reading E:\codeql\vscode-codeql-starter\codeql-go\ql\test\qlpack.yml: Unrecognized field "groups" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (14 known properties: "license", "dbscheme", "extractor", "libraryPathDependencies", "repository", "name", "upgrades", "version", "library", "description", "downgrades", "tests", "dependencies", "suites"])
                               at [Source: (StringReader); line: 2, column: 10] (through reference chain: com.semmle.frontend.packs.QlPack["groups"]) (E:\codeql\vscode-codeql-starter\codeql-go\ql\test\qlpack.yml:1,1-1)`
And I tried `git checkout codeql-cli/v2.7.2`, but it not worked.  Is this somehow broken?

**Comment by adityasharad** [comment]
This should be fixed now: could you please try updating to CodeQL 2.7.3 and updating your submodule of the starter repo?

**Comment by wulfland** [comment]
Updated `ql` and `codeql-go`to `v2.7.3` - pulled the latest version of the starter workspace and updated VSCode extension. But I get strange errors now:
 
````
com.semmle.util.exception.CatastrophicError: An error occurred during the evaluation of Locations::Location::hasLocationInfo_dispred#bfffff/6@b134d17j
The RA to evaluate was:

    {1} r1 = SCAN AST::ASTNode::getLocation_dispred#bf OUTPUT In.1
    {6} r2 = JOIN r1 WITH locations_default ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Rhs.2, Rhs.3, Rhs.4, Rhs.5
    {6} r3 = JOIN r2 WITH files ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5
    return r3

(eventual cause: CatastrophicError "Did not preallocate enough memory to allocate 17512 bytes")
```

**Comment by wulfland** [comment]
I cloned the repo to new folder and initialised the submodules. Everything works fine. Seems to be a problem with the manual checkout of the submodules.

**Comment by Aaron911** [comment]
> Updated `ql` and `codeql-go`to `v2.7.3` - pulled the latest version of the starter workspace and updated VSCode extension. But I get strange errors now:
> 
> ```
> com.semmle.util.exception.CatastrophicError: An error occurred during the evaluation of Locations::Location::hasLocationInfo_dispred#bfffff/6@b134d17j
> The RA to evaluate was:
> 
>     {1} r1 = SCAN AST::ASTNode::getLocation_dispred#bf OUTPUT In.1
>     {6} r2 = JOIN r1 WITH locations_default ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Rhs.2, Rhs.3, Rhs.4, Rhs.5
>     {6} r3 = JOIN r2 WITH files ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5
>     return r3
> 
> (eventual cause: CatastrophicError "Did not preallocate enough memory to allocate 17512 bytes")
> ```
> ```
I cloned the repo to new folder and initialised the submodules, and updated ql and codeql-go to v2.7.3, finally it worked! Thank you very much!!
